include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false
    always_use_package_imports: true
    prefer_const_constructors: true
    require_trailing_commas: true